runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /
  script: controllers.main.app

- url: /anagram/save
  script: controllers.anagram_request.app
  login: required

- url: /anagram/search
  script: controllers.anagram_request.app
  login: required

- url: /anagram/sub_anagram
  script: controllers.anagram_request.app
  login: required

- url: /anagram/upload
  script: controllers.anagram_request.app
  login: required

- url: /upload_text
  script: controllers.anagram_upload.app
  login: required

- url: /assets
  static_dir: assets
